### ISSUE TITLE
Overlap function not working in newer versions (1.2.0, 1.2.0a)

### ISSUE THREAD

**Issue by sureman** [mikessh/migec#10]
There is a problem during the Assembly step when using the --overlap option in the Checkout step.  For example,
java -jar migec-1.2.0a.jar Assemble checkout/R12.fastq.gz - assemble/ 

results in the follwing error:
[ERROR] Bad file extension -. Either .fastq, .fastq.gz or '-' should be provided as R2 file

This occurs with the batch commands as well.  Any help is much appreciated. Thank you for creating and maintaining this extremely useful program.

**Comment by mikessh** [comment]
Dear @sureman thanks a lot for the feedback. I've fixed the issue, please let me know if it works fine for you now. I've checked it on my datasets with batch commands and various `--default-mask` parameters to process read1/read2/overlapped data separately. As for now, you can get the sources and run `mvn clean install` to compile them with Maven or use `.` instead of `-`. I'm going to spend some time on some other issues and making the docs better before I'll make 1.2.1 release.

**Comment by sureman** [comment]
Thank you for addressing this so quickly.  I did not get a chance to retry 1.2.0 or 1.2.0a, but I did test my whole pipeline using 1.2.1 and I received the following output:

Executing com.milaboratory.migec.Assemble -m 8 -q 15 --assembly-mask 1:1 --filter-collisions checkout/R1.fastq.gz checkout/R2.fastq.gz assemble/
[ERROR] Bad file extension --assembly-mask. Either .fastq or .fastq.gz should be provided as R1 file.

I will try the other versions as you suggested above.

**Comment by mikessh** [comment]
Now this parameters is called simply `--mask`. Please check out the new docs for 1.2.1+, http://migec.readthedocs.org/en/latest/assemble.html#assemble-manual

**Comment by sureman** [comment]
Thanks but I did not actually input the parameter but rather used defaults during batch processing.  Below is my full script:

MIGEC="java -jar migec-1.2.1.jar"
$MIGEC CheckoutBatch -cute --overlap barcodes.txt checkout/
$MIGEC Histogram checkout/ histogram/
$MIGEC AssembleBatch checkout/ histogram/ assemble/
$MIGEC CdrBlastBatch -R TRB checkout/ assemble/ cdrblast/
$MIGEC FilterCdrBlastResultsBatch cdrblast/ filtered_cdrblast/

**Comment by sureman** [comment]
I proposed a change in AssembleBatch.groovy which seems to correct the issue on our end.  Hopefully I did it correctly!  Thanks again for your help and this great program.

**Comment by mikessh** [comment]
Thanks! I've updated the release
