### ISSUE TITLE
Unique Master-Slave barcode combinations possible?

### ISSUE THREAD

**Issue by FelixKrueger** [mikessh/migec#22]
Hi Mikhail,

We recently attempted to perform your assay for Ig profiling (Turchaninova et al. 2016) and generated libraries successfully, which were then sequenced using a Miseq with 400+100 asymmetric sequencing. We used primers that would generate the barcodes specified in this barcode.txt file:

```
Sample_ID            Master barcode sequence               Slave barcode sequence
Sample1     CGATGTcagtggtatcaacgcagagtNNNNtNNNNtNNNNtct   CGATGTattgggcagccctgatt
Sample2     TGACCAcagtggtatcaacgcagagtNNNNtNNNNtNNNNtct   TGACCAattgggcagccctgatt
Sample3     ACAGTGcagtggtatcaacgcagagtNNNNtNNNNtNNNNtct   ACAGTGattgggcagccctgatt
Sample4     GCCAATcagtggtatcaacgcagagtNNNNtNNNNtNNNNtct   GCCAATattgggcagccctgatt
Sample5     CAGATCcagtggtatcaacgcagagtNNNNtNNNNtNNNNtct   CAGATCattgggcagccctgatt
Sample6     TGACCAcagtggtatcaacgcagagtNNNNtNNNNtNNNNtct   ACAGTGattgggcagccctgatt
```

When we processed the sequences (as they came off the sequencer) using `migec` we got the following checkout.log file:

```
undef-m     6370749     6370749     null
Sample5     2364534     2198683     null
Sample6           0           0     null
Sample3     2479849     2302328     null
Sample2     4993347     2316706     null
Sample4     2334377     2195042     null
undef-s           0     3445434     null
Sample1     3650786     3364700     null
```

We were under the impression from the published protocol that samples were demultiplexed using the combination of master and slave barcodes but it would seem this is not the case and in fact, at least for the current version of `migec`, the master barcode is required to be unique. Is this correct? In our case Sample2 and Sample6 share the same Master barcode, so Sample2 has nearly twice as many hits for R1 than for R2, and Sample 6 seems to be skipped entirely.

Would it be possible to modify `migec` to allow splitting on unique Master-Slave barcode combinations. or alternatively mention the requirement for unique Master barcodes somewhere (and spit out a big fat warning message somewhere?)? Apologies if this is mentioned somewhere and we missed it. 
Many thanks! Dan & Felix

**Comment by mikessh** [comment]
Hello!

Yes the master barcodes have to be unique. Have you tried replacing Sample 6 

```
Sample6     TGACCAcagtggtatcaacgcagagtNNNNtNNNNtNNNNtct   ACAGTGattgggcagccctgatt
```

with say

```
Sample6     acAGTGATTgggcagccctgatt   TGACCAcagtggtatcaacgcagagtNNNNtNNNNtNNNNtct
```

This should resolve most of the issues - as all downstream analysis works for both strands.

**Comment by FelixKrueger** [comment]
It hasn't run to completion yet but it does indeed seem to generate output! So from this I take it that one could use `lower` and `UPPER` case to define 'uniqueness' of the barcodes even if they have the same sequence? I'm assuming this because the sequence ACAGTG does also exist as Master barcode sequence already, but acAGTG seems to work.

Many thanks for your quick help!

**Comment by mikessh** [comment]
The ``UPPER`` case letters are matched exactly. They are used to select sample ID and should be unique for master barcode. Slave barcode is used to proofread sample ID selection (e.g. protect from contamination/chimeras), it is matched exactly and non-unique slave barcodes are allowed.

The ``lower`` case letters are used to check if the matched sample index is in the multiplexing primer, the match can have some fraction errors in it (specified by parameters).

In some cases, e.g.

```
S1 ATGCcatgcatgca CATGcatgcatgca
S2 CATGcatgcatgca ATGCcatgcatgca
```

there is no way to distinguish the barcodes for non-oriented reads, for oriented reads one can use ``-o`` option.

**Comment by ChristelKrueger** [comment]
Great, thanks for your quick help!

**Comment by FelixKrueger** [comment]
Thanks for your quick help (and sorry for using the wrong account for the previous message...)

**Comment by FelixKrueger** [comment]
I just had a look at the actual output of the run, and while it did now generate some output it seems that no UMIs were written to the sequence headers which causes subsequent steps to die:

```
[Thu Apr 20 13:14:05 BST 2017 com.milaboratory.migec.Histogram] Processing Sample6 (paired)
[ERROR] no UMI header in input (@HWI-M02293:263:000000000-B3NFW:1:1101:18818:1001 1:N:0: R1). Terminating
```

Hmm, would it help if I would split the Sample 6 sequences into specific files to start with (the sample should carry a specific Truseq index), and then run the this sample with the Checkout module isolated using only the Sample6 information in the barcodes.txt file and merge them back into the results folder with the other samples later?

**Comment by mikessh** [comment]
Hmm have you used capital ``N`` in the barcodes? Only these positions are output to the header

**Comment by FelixKrueger** [comment]
Hi mikessh, 

I believe the issue had to do with the formatting of the barcodes.txt file (emacs seems to somehow add more than one tab to be consistent with other entries and that seems to screw up the UMI extraction process). I got it to work with Checkout and CheckoutBatch (they both produce the same result), in the future we are trying to avoid using the same Master barcode more than once though.

I managed to run the whole pipeline fine up to the MiXCR step, it all went swimmingly!  By the way your tools are very well nicely documented, great work

Thanks again, Felix

**Comment by mczulu** [comment]
> Hi mikessh,
> 
> I believe the issue had to do with the formatting of the barcodes.txt file (emacs seems to somehow add more than one tab to be consistent with other entries and that seems to screw up the UMI extraction process). I got it to work with Checkout and CheckoutBatch (they both produce the same result), in the future we are trying to avoid using the same Master barcode more than once though.
> 
> I managed to run the whole pipeline fine up to the MiXCR step, it all went swimmingly! By the way your tools are very well nicely documented, great work
> 
> Thanks again, Felix

I realize this post in several years old, but I am encountering the same issue as @FelixKrueger regarding the UMI extraction issue. I don't understand @mikessh 's comment "Hmm have you used capital N in the barcodes? Only these positions are output to the header. PS If you've performed de-multiplexing using Illumina indices you can specify a FASTQ file pair for each barcode combination and run CheckoutBatch (see docs)"

**Comment by FelixKrueger** [comment]
>> Additionally, @FelixKrueger, could you provide detail as to what you meant by "more than one tab"?

It's been a while, but I believe it was really something as trivial as emacs (the text editor I was using) adding several tab stop characters despite hitting the TAB key only once...

**Comment by mczulu** [comment]
Thanks Felix! I made my txt files by saving from an Excel sheet. Maybe that is the issue! I'll make fresh .txt files in a text editor and see if that does the trick.
