### ISSUE TITLE
MusMusculus TRA supported?

### ISSUE THREAD

**Issue by stevedaley** [mikessh/migec#24]
Hello Mikhail,
Is the MusMusculus TRA locus supported by MIGEC? This species/gene combination has germline sequences available in IMGT, yet it is absent from the table in the MIGEC documentation.
Regards,
Steve

**Comment by mikessh** [comment]
Likely a documentation typo, MMU TRA is supported - see https://github.com/mikessh/migec/blob/master/src/main/resources/segments.all.txt for the list of supported segments

**Comment by stevedaley** [comment]
Thanks very much for the clarification, Mikhail. Regards, Steve
