### ISSUE TITLE
No assemble.log.txt

### ISSUE THREAD

**Issue by gknit** [mikessh/migec#29]
Hi!

For some reason, I don't get the summary file from the Assemble function. Any idea why this could be the case?

I don't use MIGEC for demultiplexing. I'm doing pairwise assembly, like this:
`java -jar migec-1.2.6.jar Assemble 03_separated/Test_Sample_fwd.fastq 03_separated/Test_Sample_rev.fastq 04_assembly/`
 and it seems to work just fine, I'm getting the fastq output files, just not the summary. It is finishing with 
`[Fri Nov 24 19:43:32 CET 2017 com.milaboratory.migec.Assemble] Processed 433112 MIGs, 1186497 reads total, 0 collisions detected, assembled so far: Test_Sample_fwd.t5 62417 MIGs, 593112 reads; Test_Sample_rev.t5 53095 MIGs, 486940 reads; Overall 52700 MIGs, 574453 reads
[Fri Nov 24 19:43:32 CET 2017 com.milaboratory.migec.Assemble] Finished`.

Best,
Gero

**Comment by mikessh** [comment]
Log files are only generated when prior steps are completed properly (e.g. to get Assemble log one should have Checkout log)
