### ISSUE TITLE
Error during MIGEC CDR BLAST

### ISSUE THREAD

**Issue by RaviDandekar** [mikessh/migec#30]
Currently, we are running MIGEC on our data, which has already been demultiplexed. To account for this we modified the barcode input (in barcodes.txt) as shown bellow.

[sample ID] CAGTGgtatcaacgcagagtNNNNtNNNNtNNNNtct  ATTGggcagccctgatt

This scheme has worked for all of our samples so far. There is only one sample that is giving us an issue. 

I believe the error, displayed in the image attached, occurred during the CDR BLAST. It was able to run through MIGEC's Checkout, Histogram and  AssembleBatch commands. 

Please let me know how I can best deal with this issue. Thank you.

![migec_error_messege](https://user-images.githubusercontent.com/2481634/33639711-7c91d18a-d9e1-11e7-875a-65e851366ea2.png)

**Comment by mikessh** [comment]
Hello, it looks like there is insufficient memory for the JVM. You can fix it by increasing the available memory with, say, ``-Xmx40G`` option as follows:

``java -jar -Xmx40G migec.jar ...``

or if you're running with the shell wrapper

``migec -Xmx40G ...``

**Comment by RaviDandekar** [comment]
Thank you for your help! That fixed everything.
