### ISSUE TITLE
MiXCR or CdrBlast?

### ISSUE THREAD

**Issue by fabio-t** [mikessh/migec#33]
Hi,

I'm using MIGEC to create sequence assemblies from UMI-tagged reads. I have previously used MiXCR with great success, so I'm a bit baffled by the fact that MIGEC seems to be doing the same work after assembly (with the CdrBlast step).

Which is now recommended between the two? Is MiXCR superfluous on UMI-based consensus sequences?

**Comment by fabio-t** [comment]
In particular (although this should perhaps be asked to @dbolotin..), I wonder if one **should** use the clustering capability of MiXCR at all, when dealing with UMI-tagged sequences.

If MIGEC correctly identifies UMIs and produces consensus sequences, wouldn't any further grouping (based on CDR3 sequence similarity) be wrong, and actually create bias?

PS: the data is TRA CDR3 mouse, paired-end reads MiSeq sequencing.

**Comment by drkoryjohns** [comment]
See vdjtools and tcR packages in R for analyzing migec output results. Best, Kory

--------------------------------------------

Kory R. Johnson, MS, PhD
Staff Scientist,
Bioinformatics Section,
Information Technology Program (ITP),
Division of Intramural Research (DIR),
National Institute of Neurological Disorders & Stroke (NINDS),
National Institutes of Health (NIH),
Bethesda, Maryland

[The Human Connectome Project uses state-of-the-art neuroimaging technology to explore the connections within the human brain.]

Mailing Address:

NINDS/NIH
Clinical Center (Building 10)
Office 3B01A
9000 Rockville Pike
Bethesda, MD 20892

Contact Information:

Phone:    301-402-1956
email:       johnsonko@ninds.nih.gov<mailto:johnsonko@ninds.nih.gov>

P Green Message:

Please consider the environment before printing this e-mail.  Thank you.

Important Message:

This electronic message transmission contains information intended for the recipient only.  Such that, the information contained herein may be confidential, privaledged, or proprietary.  If you are not the intended recipient, be aware that any disclosure, copying, distribution, or use of this information is strictly prohibited.  If you have received this electronic information in error, please notify the sender immediately by telephone.  Thank you.

--------------------------------------------

**Comment by fabio-t** [comment]
Hi @drkoryjohns, I have my own sets of scripts for the later analysis. However, they rely (as vdjtools does) on a table of clones with their abundance. That is, clonotype identification.

Which tool to use to find the clonotypes is the question here. MiXCR has a clustering step that, as I've written, might not be suited to UMIs. Am I wrong?

**Comment by drkoryjohns** [comment]
If using UMI’s, use MIGEC.  Then use vdjtools and tcR packages for drill down.  The MIGEC table output includes CDR3 clones described by row in both nt and aa form along with pre umi-corrected read counts and post umi-corrected read counts.  Have found MIGEC output in conjunction with and vdjtools and tcR very useful and powerful combination.  Big thanks to the MI Laboratory team!  Looking to publish and cite soon.

--------------------------------------------

Kory R. Johnson, MS, PhD
Staff Scientist,
Bioinformatics Section,
Information Technology Program (ITP),
Division of Intramural Research (DIR),
National Institute of Neurological Disorders & Stroke (NINDS),
National Institutes of Health (NIH),
Bethesda, Maryland

[The Human Connectome Project uses state-of-the-art neuroimaging technology to explore the connections within the human brain.]

Mailing Address:

NINDS/NIH
Clinical Center (Building 10)
Office 3B01A
9000 Rockville Pike
Bethesda, MD 20892

Contact Information:

Phone:    301-402-1956
email:       johnsonko@ninds.nih.gov<mailto:johnsonko@ninds.nih.gov>

P Green Message:

Please consider the environment before printing this e-mail.  Thank you.

Important Message:

This electronic message transmission contains information intended for the recipient only.  Such that, the information contained herein may be confidential, privaledged, or proprietary.  If you are not the intended recipient, be aware that any disclosure, copying, distribution, or use of this information is strictly prohibited.  If you have received this electronic information in error, please notify the sender immediately by telephone.  Thank you.

--------------------------------------------

**Comment by fabio-t** [comment]
I see. Thanks for your input.

**Comment by fabio-t** [comment]
Sorry to reiterate this, but I've just noticed that the author's paper on November actually advises a different thing - to pipe MIGEC to MiXCR:

http://onlinelibrary.wiley.com/doi/10.1111/imm.12857/full

It would be great to have a current recommendation, @mikessh. Is MiXCR still recommended after the Assemble step? Or is CdrBlast plus filtering more likely to find the "real" clones?

**Comment by mikessh** [comment]
Well in terms of CDR3 extraction they both perform with high accuracy.

* MIGEC has additional feature to filter spurious CDR3s using both raw and assembled reads. 
* On the other hand, MIGEC doesn't map Variable FR/CDR regions & hypermutations so if you are doing full-length go for MIXCR. 

Note that you can use MIXCR both after Checkout and Assemble step. However, depending on your coverage (reads per UMI) you may consider turning off all error correction in MIXCR. I.e. if you have high-quality consensuses you don't need clonotype clustering based on parent-to-child ratio.

Hope this helps!

**Comment by fabio-t** [comment]
This is exactly what I needed. Many thanks!
