### ISSUE TITLE
how to cdrblast output results without non-functional CDR3s?

### ISSUE THREAD

**Issue by suntaosimon** [mikessh/migec#35]
I used the default command, 
java -jar migec-1.2.8.jar CdrBlast -R IGH checkout/R1.fastq.gz checkout/R2.fastq.gz cdrblast/test.cdrblast.txt

the output file contains non-coding clonotypes that contain either a stop codon or a frameshift within CDR3 sequence. How do I filter it?

I noticed FilterCdrBlastResults seem can do this, but it also need a cdrblast_result_assembled_data and a cdrblast_result_raw_data. But what are those to data?

Thanks!

**Comment by mikessh** [comment]
Hello. You can only do this with other downstream analysis software such as [VDJtools](https://github.com/mikessh/vdjtools).
