### ISSUE TITLE
Migec_1.2.7 and Migec_1.2.8

### ISSUE THREAD

**Issue by ADvorkinGheva** [mikessh/migec#37]
Hello,

I have demultiplexed paired-end fastq files (they were dumultiplexed at our sequencing facility). The barcodes were clipped from the sequences.

When trying to run migec (both 1.2.7 and 1.2.8), I get errors (please, see the attached log files).
I would greatly appreciate any advice on how to solve these.

Thank you very much!

Sincerely,
Anna
[_migec_error_2.1.7.log](https://github.com/mikessh/migec/files/1952727/_migec_error_2.1.7.log)
[_migec_error_2.1.8.log](https://github.com/mikessh/migec/files/1952728/_migec_error_2.1.8.log)

**Comment by mikessh** [comment]
Hello.

It looks like your ``checkout.filelist.txt`` is malformed and you're specifying the same path for ``checkout/`` folder and histogram output folder. You can try re-running all routines using separate folder for each analysis step, e.g. naming them exactly as in docs.
