### ISSUE TITLE
Should I use trimming tool before using migec?

### ISSUE THREAD

**Issue by gorgitko** [mikessh/migec#38]
Hello,

concretely, should I use Trimmomatic for adapter and quality trimming before using migec?

Thank you.

**Comment by mikessh** [comment]
Hello,

Nope, on contrary, it is not recommended to use adapter and quality trimming prior to running MIGEC or MIXCR. The only exception is when dealing with C region primer and isotype mapping in MIXCR (in this case it can be necessary to trim C primers to some extent).

**Comment by suntaosimon** [comment]
How about Illumina index? The sequence facility will do the demultiplex for us and what we got are the demultiplexed fastqs with index sequences trimmed. Can I still use MIGEC for UMI tag extraction for those demultiplexed samples? @mikessh

**Comment by gorgitko** [comment]
@suntaosimon Illumina indices are different from UMI tags, so you can use MIGEC - I also have demultiplexed data and MIGEC works fine.

**Comment by suntaosimon** [comment]
@gorgitko Thanks for your reply!
I tried read fastq R2 files, the Illumina index was not on the end of the reads. It directly begin with our 5RACE adaptor. It's like UMI-cDNA.
BTW, CTG in beginning of the barcodes you shows above? Is that the part of your Illumina index? And  because gcacattgatttgggagtc is α C region, I think your UMI is on the 3'? Mine is on the 5' with the adaptor.

**Comment by gorgitko** [comment]
`gcacattgatttgggagtc` is a TCR specific primer. `CTG` in the beginning is a part of adaptor sequence which wasn't removed by Illumina demultiplexer. I used it because it was common for all UMIs, something like "anchor" :wink:
UMI pipeline was adopted from http://advances.sciencemag.org/content/2/3/e1501371
[Here](http://advances.sciencemag.org/content/advances/2/3/e1501371/F2.large.jpg?width=800&height=600&carousel=1) you can see the technical details. I was using only reverse UMIs because of low quality of forward UMIs (and also I don't exactly know how to use them in MIGEC). So these barcodes are from 5' end of reads.
