### ISSUE TITLE
ERROR: Bad barcode .. Terminating

### ISSUE THREAD

**Issue by emmecola** [mikessh/migec#57]
Dear all, I am a new user of MIGEC. I'd like to analyze single-end sequencing reads from a single FASTQ file that contains reads coming from two samples. When I launch the following command I get an error (**"Bad barcode .. Terminating"**).

`java -jar ../migec-1.2.9/migec-1.2.9.jar Checkout --rc-barcodes -cute barcodes.txt NAIVE_IDX_tn.fastq . ./checkout/`

The barcodes that I am using are the following:
Sample_1: GAGANNNNNNNNNNNNAGCCACCTCCGCCTGAAC
Sample_2: GAGANNNNNNNNNNNNCTTCTTCTTGGGTGCCATG

I have tried different combinations of master/slaves, but none of them seems to work. Interestingly, the software prompts the same error even when I try to use the barcode sample table that I found in the user guide. What might be the problem according to you? Many thanks in advance.

For example I tried this barcode file. I split the barcodes into two segments (master/pair), and I've deliberately chosen the seed nucleotides. I also tried other ways (keeping the barcode as a single master sequence, using all capital letters, ..) but none of them works! Why?

Sample_ID  Master barcode sequence  Slave barcode sequence
S1  GAGANNNNNNNNNNNN  AGCCacctccgcctgaac 
S2  GAGANNNNNNNNNNNN  CTTCttcttgggtgccatg

**Comment by li1311139481** [comment]
I have same question. do you have solved it ?
