### ISSUE TITLE
Docs & release testing

### ISSUE THREAD

**Issue by mikessh** [mikessh/migec#9]
* Modify readme
* Add some examples
* Do some testing

**Comment by drkoryjohns** [comment]
Hi Mikhail, thanks for your email alert regarding the update to Migec.  Will download and implement and compare results to prior version.  Best, Kory

Sent from my iPhone

On Feb 17, 2015, at 3:55 PM, Mikhail Shugay <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #9<https://github.com/mikessh/migec/issues/9>.

�
